name: Windows 10 Dispose PC  # Updated name

on:
  workflow_dispatch:  # Trigger manually 

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Download
      run: Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
    - name: Extract
      run: Expand-Archive ngrok.zip
    - name: Create RDP User 'Disposable'
      run: | 
          net user Disposable z7mK_*=42*7I /add
          net localgroup administrators Disposable /add
    - name: Schedule Disposable User Deletion
      run: |
          $expireTime = (Get-Date).AddMinutes(1)
          $expireTimeFormatted = $expireTime.ToString("yyyy-MM-dd HH:mm:ss") 
          schtasks /create /tn "DeleteDisposableUser" /tr "net user Disposable /delete" /sc once /st $expireTimeFormatted

    - name: Auth
      run: .\ngrok\ngrok.exe authtoken 2f66jknimQGiebVkemne8MEi4vo_5sC2FLzm6mutdQQwWmbtd
    - name: Enable Remote Desktop (RDP) # Updated step names for clarity
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
    - name: Configure Firewall for RDP
      run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - name: Adjust RDP Authentication
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - name: Create RDP User
      run: Set-LocalUser -Name "Disposable" -Password (ConvertTo-SecureString -AsPlainText "z7mK_*=42*7I" -Force)
    - name: Create Tunnel
      run: .\ngrok\ngrok.exe tcp 3389 
